import { IExperienceBlock } from "./components/ExperienceBlock";

const data: IExperienceBlock[] = [
  {
    company: "Ro",
    website: "https://ro.co/",
    city: "New York, NY",
    role: "Senior Software Engineering Manager",
    from: "September 2024",
    to: "Present",
    bulletPoints: [
      "Manage a ~13-person engineering team, including 8 direct reports, responsible for Ro’s patient-facing growth platform across acquisition, onboarding, asynchronous clinical intake, treatment selection, pricing, promotions, and experimentation.",
      "Protected patient safety during ~10x growth in 18 months, leading to 0 major regressions via operationalizing launch-readiness reviews, UAT, automated acceptance tests, observability, load testing, and rollback planning.",
      "Directed delivery of a portfolio-wide roadmap across multiple care categories, including medication launches, pricing and discount experiments, onboarding optimization, retention flows, and treatment-selection improvements.",
      "Expanded the team’s scope and operating model from product-feature execution to portfolio-level platform ownership across weight management, men's health, hair loss, and other care areas.",
      "Provided hands-on technical leadership on high-risk work, authoring and reviewing targeted PRs and defining a phased pricing-experimentation strategy around automation, pricing source-of-truth centralization, and Product self-service.",
      "Built a stronger engineering bench through senior hiring, direct feedback, coaching, and ownership models that moved engineers into technical-lead roles on priority initiatives.",
    ]
  },
  {
    company: "Amazon",
    website: "https://amazon.com/",
    city: "New York, NY",
    role: "Software Development Manager",
    from: "May 2022",
    to: "September 2024",
    bulletPoints: [
      "Owned global payments engineering for Audible, leading deployment, observability, and testing capabilities for high-availability billing systems across international markets.",
      "Expanded Audible’s payment capabilities globally by leading the rollout of Apple Pay Billing and Google Play Billing across all markets, including highly regulated regions such as Japan and India.",
      "Managed and developed a 10-person engineering team responsible for distributed payments infrastructure across TypeScript/CDK, Java service-oriented architectures, and Amazon-internal platforms.",
      "Established a predictable execution model that achieved 100% of every quarterly delivery commitment, which improved planning accuracy, dependency visibility, and stakeholder confidence.",
      "Scaled team capacity through partnership with senior leadership and recruiting, hiring three engineers in the first six months.",
      "Led the team through layoffs and organizational restructuring while maintaining 100% voluntary retention and the highest internal morale score in the organization.",
    ],
  },
  {
    company: "Capsule",
    website: "https://capsule.com",
    city: "New York, NY",
    role: "Software Engineering Manager",
    from: "April 2019",
    to: "May 2022",
    bulletPoints: [
      "Owned engineering delivery for Capsule’s consumer-facing digital platforms, leading a 13-person team across web, iOS, and Android applications.",
      "Scaled the team from 5 engineers through 20+ hires, then designed and executed successive team splits that created dedicated Test Engineering and Acquisitions functions.",
      "Expanded engineering leadership capacity by transitioning newly formed teams to incoming managers, enabling the organization to scale beyond a single-team model.",
      "Drove a full TypeScript migration across Capsule’s user-facing product surface area, standardizing the frontend architecture and improving maintainability across web and mobile-adjacent systems.",
      "Established the organization’s CI/CD and automated testing foundation using Jenkins and Cypress, creating a reusable pipeline model adopted by other engineering teams.",
      "Designed and evolved three generations of deployment and scaling infrastructure to support Capsule’s growing consumer product footprint.",
      "Led development of Capsule’s order status and courier tracking platform, increasing customer transparency across prescription fulfillment and last-mile delivery workflows.",
    ],
  },
  {
    company: "IPSoft",
    website: "https://www.ipsoft.com",
    city: "New York, NY",
    role: "Technical Lead",
    from: "August 2017",
    to: "August 2018",
    bulletPoints: [
      "Engineered a chat application for customer service via AI, in React/Redux",
      "Managed projects and priorities using SCRUM for a team of 5 front-end developers",
      "Reduced build time from 7 minutes to 12 seconds by rebuilding build process with Webpack and Babel",
      "Created new user interface components like pie charts, data masking, and action buttons",
      "Rebuilt Bamboo CI/CD pipeline, streamlined merge -> build -> release -> deployment process",
      "Created reproducible builds with Yarn",
      "Worked with clients and internal stakeholders to create roadmaps, groom feature set, and change our development cycles to better meet their needs",
      "Made user interface client-customizable, eliminating the need for separate per-client builds and allowing developers to do development instead of operations",
    ],
  },
  {
    company: "Apprenda LLC",
    website: "https://apprenda.com",
    from: "September 2015",
    to: "February 2017",
    city: "New York, NY",
    role: "Software Engineer",
    bulletPoints: [
      "Apprenda built a competitor to Kubernetes, before k8s existed, and the team went on to make up much of the CNCF and Heptio engineering teams",
      "Led a project to perform in-place, zero-downtime upgrades of the Apprenda platform, collaborating with nearly a dozen engineers in addition to dedicated QA, Product, and Documentation personnel",
      "Led a project to create a central hub for logs/environmental instrumentation of test server networks using the ELK stack and Docker/docker-compose",
      "Utilized Vagrant, Packer, and Chef to spin up user-defined multi-node environments for testing our Platform-as-a-Service directly on developer machines, shortening a 24 hour build-test cycle to 20 minutes",
      "Wrote MSI installation packages (and a new build process around them) to install critical Apprenda services",
      "Product owner for multiple critical tools, such as a command line client for interacting with and scripting the platform, a tool for bulk loading data (users, subscriptions, applications) into the platform, and our mission-critical, failure-tolerant Installer/Upgrader/Uninstaller desktop application (which has more than 150,000 LOC)",
      "Worked in Go, Python, C#, Bash, Scala, and Powershell",
    ],
  },
  {
    company: "QueBIT Consulting LLC",
    website: "https://quebit.com",
    from: "March 2013",
    to: "September 2015",
    city: "New York, NY",
    role: "Full Stack Engineer",
    bulletPoints: [
      "Worked as a full stack engineer on a tool that let financial professionals easily create realtime web dashboards from Excel spreadsheets",
      "Architected design to allow for reading from any Workbook source such as Google Docs, Apple Numbers, OpenOffice (Factory took a Provider, Provider implemented Interface of reading methods)",
      "Extended DotNetHighCharts API (a HighCharts definition creation library in C#) to produce interactive, data-driven maps (through HighMaps) in JavaScript",
      "Massively refactored the existing code base by encapsulating common code, removing unused historical functions, and splitting large classes to clarify and simplify program flow",
      "Served as primary engineer for a tool to produce scheduled/daily reporting on financial data from TM1 (ReportWORQ). Provided assistance to customers during outages, gathered feedback/implemented improvements, and managed client expectations",
      "Improved data load speed by 250+ times by using batch data pulling to reduce the number of roundtrips over the network/to TM1",
      "Implemented Change-awareness flags/dirty checking across the entire object model to only save deltas which increased save speed by 100+ times",
      "Heavily modified existing Excel Expression evaluator, an Expression-to-C# compiler: Rebuilt expression parsing and AST Abstract Syntax Tree creation, transversal logic, and removed deprecated logical nodes",
      "Used JMeter to stress test, analyze, and report on web page performance under arbitrary loads to ensure Nielsen Ratings could provide an acceptable user experience with their existing hardware configuration with 2,000+ concurrent TM1 users",
      "Reverse engineered the method flow of TM1Web, to spoof authentication, manipulate data, request specific pages based on user input, and log out, while analyzing performance of each step",
    ],
  },
  {
    company: "Raytheon Technologies",
    city: "Windsor Locks, CT",
    role: "Supply Chain Analyst/Co-op",
    from: "January 2012",
    to: "September 2012",
    website: "https://www.rtx.com",
    bulletPoints: [
      "Managed purchasing and logistics for a procurement vertical",
      "Performed analytics and reporting on operational statistics using SQL queries + visualization tools",
      "Maintained supplier relationships and identified new supplier spend opportunities",
    ],
  },
];

export default data;
